/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorpusPriveRouteImport } from './routes/corpus-prive'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as ModeleIdRouteImport } from './routes/modele.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusPriveRoute = CorpusPriveRouteImport.update({
  id: '/corpus-prive',
  path: '/corpus-prive',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeleIdRoute = ModeleIdRouteImport.update({
  id: '/modele/$id',
  path: '/modele/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpus-prive': typeof CorpusPriveRoute
  '/methodologie': typeof MethodologieRoute
  '/questions': typeof QuestionsRoute
  '/modele/$id': typeof ModeleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpus-prive': typeof CorpusPriveRoute
  '/methodologie': typeof MethodologieRoute
  '/questions': typeof QuestionsRoute
  '/modele/$id': typeof ModeleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpus-prive': typeof CorpusPriveRoute
  '/methodologie': typeof MethodologieRoute
  '/questions': typeof QuestionsRoute
  '/modele/$id': typeof ModeleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/corpus-prive' | '/methodologie' | '/questions' | '/modele/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corpus-prive' | '/methodologie' | '/questions' | '/modele/$id'
  id:
    | '__root__'
    | '/'
    | '/corpus-prive'
    | '/methodologie'
    | '/questions'
    | '/modele/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorpusPriveRoute: typeof CorpusPriveRoute
  MethodologieRoute: typeof MethodologieRoute
  QuestionsRoute: typeof QuestionsRoute
  ModeleIdRoute: typeof ModeleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus-prive': {
      id: '/corpus-prive'
      path: '/corpus-prive'
      fullPath: '/corpus-prive'
      preLoaderRoute: typeof CorpusPriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modele/$id': {
      id: '/modele/$id'
      path: '/modele/$id'
      fullPath: '/modele/$id'
      preLoaderRoute: typeof ModeleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorpusPriveRoute: CorpusPriveRoute,
  MethodologieRoute: MethodologieRoute,
  QuestionsRoute: QuestionsRoute,
  ModeleIdRoute: ModeleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
