/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivateBenchmarkRouteImport } from './routes/private-benchmark'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as ModelIdRouteImport } from './routes/model.$id'
import { Route as QuestionIdRouteImport } from './routes/question.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateBenchmarkRoute = PrivateBenchmarkRouteImport.update({
  id: '/private-benchmark',
  path: '/private-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelIdRoute = ModelIdRouteImport.update({
  id: '/model/$id',
  path: '/model/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionIdRoute = QuestionIdRouteImport.update({
  id: '/question/$id',
  path: '/question/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/private-benchmark': typeof PrivateBenchmarkRoute
  '/questions': typeof QuestionsRoute
  '/model/$id': typeof ModelIdRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/private-benchmark': typeof PrivateBenchmarkRoute
  '/questions': typeof QuestionsRoute
  '/model/$id': typeof ModelIdRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/private-benchmark': typeof PrivateBenchmarkRoute
  '/questions': typeof QuestionsRoute
  '/model/$id': typeof ModelIdRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/methodology'
    | '/private-benchmark'
    | '/questions'
    | '/model/$id'
    | '/question/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/methodology'
    | '/private-benchmark'
    | '/questions'
    | '/model/$id'
    | '/question/$id'
  id:
    | '__root__'
    | '/'
    | '/methodology'
    | '/private-benchmark'
    | '/questions'
    | '/model/$id'
    | '/question/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivateBenchmarkRoute: typeof PrivateBenchmarkRoute
  QuestionsRoute: typeof QuestionsRoute
  ModelIdRoute: typeof ModelIdRoute
  QuestionIdRoute: typeof QuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-benchmark': {
      id: '/private-benchmark'
      path: '/private-benchmark'
      fullPath: '/private-benchmark'
      preLoaderRoute: typeof PrivateBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model/$id': {
      id: '/model/$id'
      path: '/model/$id'
      fullPath: '/model/$id'
      preLoaderRoute: typeof ModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/$id': {
      id: '/question/$id'
      path: '/question/$id'
      fullPath: '/question/$id'
      preLoaderRoute: typeof QuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodologyRoute: MethodologyRoute,
  PrivateBenchmarkRoute: PrivateBenchmarkRoute,
  QuestionsRoute: QuestionsRoute,
  ModelIdRoute: ModelIdRoute,
  QuestionIdRoute: QuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
