/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as FailuresRouteImport } from './routes/failures'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivateBenchmarkRouteImport } from './routes/private-benchmark'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as TestRouteImport } from './routes/test'
import { Route as ModelIdRouteImport } from './routes/model.$id'
import { Route as QuestionIdRouteImport } from './routes/question.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const FailuresRoute = FailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateBenchmarkRoute = PrivateBenchmarkRouteImport.update({
  id: '/private-benchmark',
  path: '/private-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelIdRoute = ModelIdRouteImport.update({
  id: '/model/$id',
  path: '/model/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionIdRoute = QuestionIdRouteImport.update({
  id: '/question/$id',
  path: '/question/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/benchmark': typeof BenchmarkRoute
  '/failures': typeof FailuresRoute
  '/import': typeof ImportRoute
  '/methodology': typeof MethodologyRoute
  '/private-benchmark': typeof PrivateBenchmarkRoute
  '/questions': typeof QuestionsRoute
  '/test': typeof TestRoute
  '/model/$id': typeof ModelIdRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/benchmark': typeof BenchmarkRoute
  '/failures': typeof FailuresRoute
  '/import': typeof ImportRoute
  '/methodology': typeof MethodologyRoute
  '/private-benchmark': typeof PrivateBenchmarkRoute
  '/questions': typeof QuestionsRoute
  '/test': typeof TestRoute
  '/model/$id': typeof ModelIdRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/benchmark': typeof BenchmarkRoute
  '/failures': typeof FailuresRoute
  '/import': typeof ImportRoute
  '/methodology': typeof MethodologyRoute
  '/private-benchmark': typeof PrivateBenchmarkRoute
  '/questions': typeof QuestionsRoute
  '/test': typeof TestRoute
  '/model/$id': typeof ModelIdRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/benchmark'
    | '/failures'
    | '/import'
    | '/methodology'
    | '/private-benchmark'
    | '/questions'
    | '/test'
    | '/model/$id'
    | '/question/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/benchmark'
    | '/failures'
    | '/import'
    | '/methodology'
    | '/private-benchmark'
    | '/questions'
    | '/test'
    | '/model/$id'
    | '/question/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/benchmark'
    | '/failures'
    | '/import'
    | '/methodology'
    | '/private-benchmark'
    | '/questions'
    | '/test'
    | '/model/$id'
    | '/question/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  BenchmarkRoute: typeof BenchmarkRoute
  FailuresRoute: typeof FailuresRoute
  ImportRoute: typeof ImportRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivateBenchmarkRoute: typeof PrivateBenchmarkRoute
  QuestionsRoute: typeof QuestionsRoute
  TestRoute: typeof TestRoute
  ModelIdRoute: typeof ModelIdRoute
  QuestionIdRoute: typeof QuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failures': {
      id: '/failures'
      path: '/failures'
      fullPath: '/failures'
      preLoaderRoute: typeof FailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-benchmark': {
      id: '/private-benchmark'
      path: '/private-benchmark'
      fullPath: '/private-benchmark'
      preLoaderRoute: typeof PrivateBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model/$id': {
      id: '/model/$id'
      path: '/model/$id'
      fullPath: '/model/$id'
      preLoaderRoute: typeof ModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/$id': {
      id: '/question/$id'
      path: '/question/$id'
      fullPath: '/question/$id'
      preLoaderRoute: typeof QuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  BenchmarkRoute: BenchmarkRoute,
  FailuresRoute: FailuresRoute,
  ImportRoute: ImportRoute,
  MethodologyRoute: MethodologyRoute,
  PrivateBenchmarkRoute: PrivateBenchmarkRoute,
  QuestionsRoute: QuestionsRoute,
  TestRoute: TestRoute,
  ModelIdRoute: ModelIdRoute,
  QuestionIdRoute: QuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
